#!/usr/bin/env bash
set -euo pipefail

# ╔═══════════════════════════════════════════════════════════════╗
# ║  Ralphton Harness — Environment Bootstrap                    ║
# ║  Detects project type and writes .harness-config             ║
# ╚═══════════════════════════════════════════════════════════════╝

CONFIG_FILE=".harness-config"

echo "=== Ralphton Harness Init ==="

# ─── Git init ────────────────────────────────────────────────────
if [ ! -d ".git" ]; then
  echo "[init] Initializing git repository..."
  git init
  git add -A
  git commit -m "init: project bootstrap" --allow-empty
fi

# ─── Detect project type ────────────────────────────────────────
PROJECT_TYPE="unknown"
BUILD_CMD=""
TEST_CMD=""
LINT_CMD=""
TYPECHECK_CMD=""
PKG_MGR=""
SRC_DIRS="src/ lib/"
TEST_DIRS="tests/ test/ __tests__/ spec/"
DETECTED_FILES=""
CHUB_AVAILABLE="false"

# Check for multiple project files (warn on ambiguity)
for f in package.json pyproject.toml requirements.txt setup.py Cargo.toml go.mod pom.xml build.gradle build.gradle.kts; do
  [ -f "$f" ] && DETECTED_FILES="${DETECTED_FILES} $f"
done
DETECTED_COUNT=$(echo "$DETECTED_FILES" | wc -w | tr -d ' ')
if [ "$DETECTED_COUNT" -gt 1 ]; then
  echo "[init] WARNING: Multiple project files detected:${DETECTED_FILES}"
  echo "[init] Using first match. Edit $CONFIG_FILE manually if incorrect."
fi

if [ -f "package.json" ]; then
  PROJECT_TYPE="node"
  if [ -f "bun.lockb" ] || [ -f "bun.lock" ]; then
    PKG_MGR="bun"
  elif [ -f "pnpm-lock.yaml" ]; then
    PKG_MGR="pnpm"
  elif [ -f "yarn.lock" ]; then
    PKG_MGR="yarn"
  else
    PKG_MGR="npm"
  fi
  BUILD_CMD="$PKG_MGR run build"
  TEST_CMD="$PKG_MGR test"
  LINT_CMD="$PKG_MGR run lint"
  if [ -f "tsconfig.json" ]; then
    TYPECHECK_CMD="$PKG_MGR run tsc --noEmit 2>/dev/null || npx tsc --noEmit"
  fi
  SRC_DIRS="src/ lib/ app/ components/"
  TEST_DIRS="tests/ test/ __tests__/ spec/"

elif [ -f "pyproject.toml" ]; then
  PROJECT_TYPE="python-uv"
  PKG_MGR="uv"
  BUILD_CMD="uv build"
  TEST_CMD="uv run pytest"
  LINT_CMD="uv run ruff check ."
  TYPECHECK_CMD="uv run mypy . 2>/dev/null || true"
  SRC_DIRS="src/ lib/"
  TEST_DIRS="tests/ test/"

elif [ -f "requirements.txt" ] || [ -f "setup.py" ]; then
  PROJECT_TYPE="python-pip"
  PKG_MGR="pip"
  BUILD_CMD="pip install -e ."
  TEST_CMD="pytest"
  LINT_CMD="ruff check . 2>/dev/null || flake8 . 2>/dev/null || true"
  TYPECHECK_CMD="mypy . 2>/dev/null || true"
  SRC_DIRS="src/ lib/"
  TEST_DIRS="tests/ test/"

elif [ -f "Cargo.toml" ]; then
  PROJECT_TYPE="rust"
  PKG_MGR="cargo"
  BUILD_CMD="cargo build"
  TEST_CMD="cargo test"
  LINT_CMD="cargo clippy -- -D warnings"
  TYPECHECK_CMD="cargo check"
  SRC_DIRS="src/"
  TEST_DIRS="tests/"

elif [ -f "go.mod" ]; then
  PROJECT_TYPE="go"
  PKG_MGR="go"
  BUILD_CMD="go build ./..."
  TEST_CMD="go test ./..."
  LINT_CMD="golangci-lint run 2>/dev/null || true"
  TYPECHECK_CMD="go vet ./..."
  SRC_DIRS="cmd/ internal/ pkg/"
  TEST_DIRS=""

elif [ -f "pom.xml" ]; then
  PROJECT_TYPE="java-maven"
  PKG_MGR="mvn"
  BUILD_CMD="mvn compile"
  TEST_CMD="mvn test"
  LINT_CMD="mvn checkstyle:check 2>/dev/null || true"
  TYPECHECK_CMD="mvn compile"
  SRC_DIRS="src/main/"
  TEST_DIRS="src/test/"

elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
  PROJECT_TYPE="java-gradle"
  PKG_MGR="gradle"
  BUILD_CMD="./gradlew build"
  TEST_CMD="./gradlew test"
  LINT_CMD="./gradlew check"
  TYPECHECK_CMD="./gradlew compileJava"
  SRC_DIRS="src/main/"
  TEST_DIRS="src/test/"
fi

echo "[init] Detected project type: $PROJECT_TYPE"

# ─── Write .harness-config (single source of truth) ─────────────
cat > "$CONFIG_FILE" << CONFIG_EOF
# Harness Configuration — generated by init.sh
# Edit this file to override auto-detected settings.
# Hooks and loop.sh read from this file.

PROJECT_TYPE="$PROJECT_TYPE"
PKG_MGR="$PKG_MGR"

# Commands (used by hooks and prompts)
BUILD_CMD="$BUILD_CMD"
TEST_CMD="$TEST_CMD"
LINT_CMD="$LINT_CMD"
TYPECHECK_CMD="$TYPECHECK_CMD"

# Directories to scan for code/tests
SRC_DIRS="$SRC_DIRS"
TEST_DIRS="$TEST_DIRS"

# Model configuration
OPUS_MODEL="\${OPUS_MODEL:-opus}"
SONNET_MODEL="\${SONNET_MODEL:-sonnet}"

# Pricing (USD per token, update as needed)
OPUS_INPUT_PRICE=0.000015
OPUS_OUTPUT_PRICE=0.000075
SONNET_INPUT_PRICE=0.000003
SONNET_OUTPUT_PRICE=0.000015

# Ambiguity threshold for Socratic → Plan transition
AMBIGUITY_THRESHOLD=0.10

# Test code ratio target
TEST_CODE_RATIO_TARGET=0.70

# Context Hub (chub) — fetch API docs for agents
CHUB_AVAILABLE="${CHUB_AVAILABLE}"
CHUB_CONTEXT_DIR=".context"
CONFIG_EOF
echo "[init] Created $CONFIG_FILE"

# ─── Update CLAUDE.md ────────────────────────────────────────────
if [ -f "CLAUDE.md" ]; then
  cat > CLAUDE.md << 'CLAUDE_EOF'
# Project Rules

## Build & Test
Commands are defined in `.harness-config`. Run `cat .harness-config` to see current settings.

## Conventions
- Read AGENTS.md for operational guide
- Read IMPLEMENTATION_PLAN.md for current task state
- Read progress.txt for recent session context
- Read CLARITY_LOG.md for resolved ambiguities from Socratic phase

## Rules
- ONE task per session. Pick the highest-priority TODO from IMPLEMENTATION_PLAN.md
- Search before assuming something isn't implemented
- Write tests alongside implementation. Target: 70% test code
- Capture the WHY in commit messages, not just the what
- Keep AGENTS.md under 60 lines. State goes in IMPLEMENTATION_PLAN.md
- Implement completely. No placeholders, no stubs, no TODOs in code
- If unrelated tests fail, fix them in this session

## Backpressure
All must pass before committing:
1. Typecheck (if applicable)
2. Lint (if applicable)
3. All tests pass
4. No `it.skip`, `@pytest.mark.skip`, or disabled tests unless documented in IMPLEMENTATION_PLAN.md
CLAUDE_EOF
  echo "[init] Updated CLAUDE.md"
fi

# ─── Update AGENTS.md (only if no agent-added content exists) ─────
if [ ! -f "AGENTS.md" ] || grep -q "Updated by agents" AGENTS.md 2>/dev/null; then
  # AGENTS.md doesn't exist or still has placeholder — safe to overwrite
  cat > AGENTS.md << AGENTS_EOF
# Operational Guide

## How to Run
\`\`\`bash
# Build
$BUILD_CMD

# Run tests
$TEST_CMD

# Lint
$LINT_CMD

# Typecheck
$TYPECHECK_CMD
\`\`\`

## Project Type
$PROJECT_TYPE (package manager: $PKG_MGR)

## Architecture Decisions
<!-- Updated by agents during build phase -->

## Patterns to Follow
- Single source of truth: no adapters, no migrations
- Test-first: write test → implement → verify
- Atomic commits: one logical change per commit

## Anti-Patterns
- Don't duplicate utilities — check shared code first
- Don't modify test assertions to make tests pass
- Don't leave console.log/print debugging statements
AGENTS_EOF
  echo "[init] Updated AGENTS.md"
fi

# ─── Create initial files ───────────────────────────────────────
if [ ! -f "progress.txt" ]; then
  echo "=== Harness initialized: $(date -Iseconds) ===" > progress.txt
  echo "Project type: $PROJECT_TYPE" >> progress.txt
  echo "[init] Created progress.txt"
fi

# ─── Create specs directory ──────────────────────────────────────
mkdir -p specs
if [ -z "$(ls -A specs/ 2>/dev/null)" ]; then
  echo "[init] WARNING: specs/ is empty. Write your specs before running the harness!"
  echo "  Example: specs/my-feature.md"
fi

# ─── Write hooks (read from .harness-config) ─────────────────────
mkdir -p hooks

cat > hooks/backpressure.sh << 'HOOK_EOF'
#!/usr/bin/env bash
# Post-tool backpressure hook — reads commands from .harness-config
# Exit 0 = success (silent), Exit 2 = error (agent re-enters to fix)

cd "${CLAUDE_PROJECT_DIR:-.}"

# Load config
CONFIG=".harness-config"
if [ -f "$CONFIG" ]; then
  # shellcheck disable=SC1090
  source "$CONFIG"
fi

ERRORS=""

# Typecheck
if [ -n "${TYPECHECK_CMD:-}" ] && [ "$TYPECHECK_CMD" != "" ]; then
  OUTPUT=$(timeout 60 bash -c "$TYPECHECK_CMD" 2>&1) || ERRORS="${ERRORS}\n=== TypeCheck Errors ===\n${OUTPUT}\n"
fi

# Lint
if [ -n "${LINT_CMD:-}" ] && [ "$LINT_CMD" != "" ]; then
  OUTPUT=$(timeout 60 bash -c "$LINT_CMD" 2>&1) || ERRORS="${ERRORS}\n=== Lint Errors ===\n${OUTPUT}\n"
fi

if [ -n "$ERRORS" ]; then
  echo -e "$ERRORS" >&2
  exit 2
fi

exit 0
HOOK_EOF
chmod +x hooks/backpressure.sh

cat > hooks/pre-commit-gate.sh << 'HOOK_EOF'
#!/usr/bin/env bash
# Pre-commit gate — reads commands from .harness-config
# Exit 0 = allow commit, Exit 2 = block (agent must fix)

cd "${CLAUDE_PROJECT_DIR:-.}"

# Load config
CONFIG=".harness-config"
if [ -f "$CONFIG" ]; then
  # shellcheck disable=SC1090
  source "$CONFIG"
fi

echo "[gate] Running pre-commit checks..."

# Run tests
if [ -n "${TEST_CMD:-}" ] && [ "$TEST_CMD" != "" ]; then
  timeout 120 bash -c "$TEST_CMD" 2>&1 || { echo "[gate] Tests failed" >&2; exit 2; }
fi

# Check for skip markers in all known source/test dirs
ALL_DIRS="${SRC_DIRS:-src/} ${TEST_DIRS:-tests/}"
EXISTING_DIRS=""
for d in $ALL_DIRS; do
  [ -d "$d" ] && EXISTING_DIRS="$EXISTING_DIRS $d"
done

if [ -n "$EXISTING_DIRS" ]; then
  # shellcheck disable=SC2086
  SKIP_MARKERS=$(grep -rn 'it\.skip\|describe\.skip\|@pytest\.mark\.skip\|@Disabled\|@Ignore' $EXISTING_DIRS 2>/dev/null | head -5)
  if [ -n "$SKIP_MARKERS" ]; then
    echo "[gate] ERROR: Skipped tests found:" >&2
    echo "$SKIP_MARKERS" >&2
    exit 2
  fi
fi

# Check for TODO/FIXME in code (not in tests or docs)
SRC_ONLY="${SRC_DIRS:-src/}"
EXISTING_SRC=""
for d in $SRC_ONLY; do
  [ -d "$d" ] && EXISTING_SRC="$EXISTING_SRC $d"
done

if [ -n "$EXISTING_SRC" ]; then
  # shellcheck disable=SC2086
  TODO_MARKERS=$(grep -rn 'TODO\|FIXME\|XXX\|HACK' $EXISTING_SRC 2>/dev/null | grep -v 'node_modules\|__pycache__\|target/' | head -5)
  if [ -n "$TODO_MARKERS" ]; then
    echo "[gate] ERROR: TODO/FIXME markers found in source:" >&2
    echo "$TODO_MARKERS" >&2
    exit 2
  fi
fi

echo "[gate] All checks passed"
exit 0
HOOK_EOF
chmod +x hooks/pre-commit-gate.sh

echo "[init] Created hook scripts (reading from $CONFIG_FILE)"

# ─── Create log directory ────────────────────────────────────────
mkdir -p .harness-logs

# ─── Save specs hash baseline ────────────────────────────────────
if [ -d "specs" ] && [ -n "$(ls -A specs/ 2>/dev/null)" ]; then
  if command -v md5sum &>/dev/null; then
    find specs/ -type f | sort | xargs md5sum 2>/dev/null | md5sum | cut -d' ' -f1 > .harness-logs/specs.hash
  elif command -v md5 &>/dev/null; then
    find specs/ -type f | sort | xargs md5 -q 2>/dev/null | md5 -q > .harness-logs/specs.hash
  fi
  echo "[init] Saved specs hash baseline"
fi

# ─── .gitignore ──────────────────────────────────────────────────
GITIGNORE_ENTRIES=(".harness-logs/" "*.bak" ".context/")
for entry in "${GITIGNORE_ENTRIES[@]}"; do
  if ! grep -qF "$entry" .gitignore 2>/dev/null; then
    echo "$entry" >> .gitignore
  fi
done

# ─── Context Hub (chub) setup ─────────────────────────────────────
if command -v chub &>/dev/null; then
  echo "[init] chub found: $(chub --version 2>/dev/null || echo 'installed')"
  CHUB_AVAILABLE="true"
elif command -v npx &>/dev/null; then
  echo "[init] chub not installed globally, will use npx @aisuite/chub"
  CHUB_AVAILABLE="npx"
else
  echo "[init] WARNING: chub (context-hub) not available. Install with: npm install -g @aisuite/chub"
  CHUB_AVAILABLE="false"
fi

# Pre-fetch docs for detected project type
if [ "$CHUB_AVAILABLE" != "false" ]; then
  CHUB_CMD="chub"
  [ "$CHUB_AVAILABLE" = "npx" ] && CHUB_CMD="npx -y @aisuite/chub"

  mkdir -p .context

  # Map project type → likely doc search terms
  CHUB_TAGS=""
  case "$PROJECT_TYPE" in
    node)           CHUB_TAGS="node,javascript,typescript" ;;
    python-uv|python-pip) CHUB_TAGS="python" ;;
    rust)           CHUB_TAGS="rust" ;;
    go)             CHUB_TAGS="go,golang" ;;
    java-maven|java-gradle) CHUB_TAGS="java" ;;
  esac

  if [ -n "$CHUB_TAGS" ]; then
    echo "[init] Searching context-hub for $CHUB_TAGS docs..."
    $CHUB_CMD search --tags "$CHUB_TAGS" --json > .context/chub-registry.json 2>/dev/null || true
    echo "[init] Saved available docs index to .context/chub-registry.json"
  fi
fi

# ─── Summary ─────────────────────────────────────────────────────
echo ""
echo "=== Init Complete ==="
echo "  Project:    $PROJECT_TYPE ($PKG_MGR)"
echo "  Config:     $CONFIG_FILE"
echo "  Build:      $BUILD_CMD"
echo "  Test:       $TEST_CMD"
echo "  Lint:       $LINT_CMD"
echo "  Typecheck:  $TYPECHECK_CMD"
echo "  Context Hub: $CHUB_AVAILABLE"
echo ""
echo "Next steps:"
echo "  1. Write specs in specs/ directory"
echo "  2. Review/edit $CONFIG_FILE if needed"
echo "  3. Run: bash loop.sh"
