spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employeedb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  threads:
    virtual:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
